<h1><center>Введение в анализ данных</center></h1>
<hr>
<h2><center>Rossman Store Sales</center></h2>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (12,5)

<h2>Подготовка данных:</h2>

<h3>Основная таблица</h3>

In [101]:
filepath = '/media/ivan/Acer/Ivan/sphere/Rossman/train.csv'
df = pd.read_csv(filepath, sep=',')
df.head()

Store  DayOfWeek        Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5  2015-07-31   5263        555     1      1            0   
1      2          5  2015-07-31   6064        625     1      1            0   
2      3          5  2015-07-31   8314        821     1      1            0   
3      4          5  2015-07-31  13995       1498     1      1            0   
4      5          5  2015-07-31   4822        559     1      1            0   

   SchoolHoliday  
0              1  
1              1  
2              1  
3              1  
4              1

In [226]:
df['Store'].unique().shape

(1115,)

In [ ]:
df['Store'].unique()

Судя по описанию, переменная StateHoliday является категориальной, поэтому преобразуем ее с помощью OneHotEncoder:

In [27]:
#from sklearn.preprocessing import OneHotEncoder

In [103]:
df = df.replace({'StateHoliday': {'0': 0, 'a': 1, 'b': 1, 'c': 1}})

И преобразуем этот столбец:

In [58]:
#state_holiday = OneHotEncoder().fit_transform(df['StateHoliday'].values.reshape(-1, 1)).toarray().astype(int)

#for i in xrange(len(state_holiday[0])):
#    df['state_holiday_type_{}'.format(i)] = state_holiday[:,i]

Удаляем уже ненужный столбец StateHoliday

In [61]:
#df.drop(df[['StateHoliday']], axis=1, inplace=True)

In [105]:
df.head()

Store  DayOfWeek        Date  Sales  Customers  Open  Promo  StateHoliday  \
0      1          5  2015-07-31   5263        555     1      1             0   
1      2          5  2015-07-31   6064        625     1      1             0   
2      3          5  2015-07-31   8314        821     1      1             0   
3      4          5  2015-07-31  13995       1498     1      1             0   
4      5          5  2015-07-31   4822        559     1      1             0   

   SchoolHoliday  
0              1  
1              1  
2              1  
3              1  
4              1

In [106]:
X = np.array(df.iloc[:,[0, 1]+range(5,9)])
y = np.array(df.loc[:,'Sales'])

In [149]:
X.shape

(1017209, 6)

In [228]:
df['DayOfWeek'].unique()

array([5, 4, 3, 2, 1, 7, 6])

In [356]:
df['Sales'].mean()

5773.818972305593

<h3>Дополнительная таблица</h3>

In [212]:
filepath = '/media/ivan/Acer/Ivan/sphere/Rossman/store.csv'
df_store = pd.read_csv(filepath, sep=',')
df_store.head()

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c          a               1270.0                        9.0   
1      2         a          a                570.0                       11.0   
2      3         a          a              14130.0                       12.0   
3      4         c          c                620.0                        9.0   
4      5         a          a              29910.0                        4.0   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                    2008.0       0              NaN              NaN   
1                    2007.0       1             13.0           2010.0   
2                    2006.0       1             14.0           2011.0   
3                    2009.0       0              NaN              NaN   
4                    2015.0       0              NaN              NaN   

     PromoInterval  
0              NaN  
1  Jan,Apr,Jul,Oct  
2  Jan,Apr,Jul,Oct  
3              NaN  
4              NaN

In [224]:
len(df_store)

1115

In [225]:
df_store['Store'].unique().shape

(1115,)

In [222]:
df_store = df_store.replace({'StoreType': {'a': 0, 'b': 1, 'c': 2, 'd': 3}})
df_store = df_store.replace({'Assortment': {'a': 0, 'b': 1, 'c': 2}})

In [229]:
df_full = df.merge(df_store, on='Store', how='left')
df_full.head()

Store  DayOfWeek        Date  Sales  Customers  Open  Promo  StateHoliday  \
0      1          5  2015-07-31   5263        555     1      1             0   
1      2          5  2015-07-31   6064        625     1      1             0   
2      3          5  2015-07-31   8314        821     1      1             0   
3      4          5  2015-07-31  13995       1498     1      1             0   
4      5          5  2015-07-31   4822        559     1      1             0   

   SchoolHoliday  StoreType  Assortment  CompetitionDistance  \
0              1          2           0               1270.0   
1              1          0           0                570.0   
2              1          0           0              14130.0   
3              1          2           2                620.0   
4              1          0           0              29910.0   

   CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
0                        9.0                    2008.0       0   
1                       11.0                    2007.0       1   
2                       12.0                    2006.0       1   
3                        9.0                    2009.0       0   
4                        4.0                    2015.0       0   

   Promo2SinceWeek  Promo2SinceYear    PromoInterval  
0              NaN              NaN              NaN  
1             13.0           2010.0  Jan,Apr,Jul,Oct  
2             14.0           2011.0  Jan,Apr,Jul,Oct  
3              NaN              NaN              NaN  
4              NaN              NaN              NaN

In [249]:
columns = ['Store', 'DayOfWeek', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance']
X_full = np.array(df_full.loc[:,columns]).astype(int)
y_full = np.array(df_full.loc[:,'Sales'])

In [269]:
X_full.shape

(1017209, 9)

<h3>Тестовые данные</h3>

In [257]:
filepath = '/media/ivan/Acer/Ivan/sphere/Rossman/test.csv'
df_test = pd.read_csv(filepath, sep=',').set_index('Id')
df_test.head()

Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
Id                                                                       
1       1          4  2015-09-17   1.0      1            0              0
2       3          4  2015-09-17   1.0      1            0              0
3       7          4  2015-09-17   1.0      1            0              0
4       8          4  2015-09-17   1.0      1            0              0
5       9          4  2015-09-17   1.0      1            0              0

In [258]:
df_test['StateHoliday'].unique()

array(['0', 'a'], dtype=object)

Такая же предобработка с тестовыми данными:

In [259]:
df_test = df_test.replace({'StateHoliday': {'0': 0, 'a': 1, 'b': 1, 'c': 1}})

#state_holiday = OneHotEncoder().fit_transform(df_test['StateHoliday'].values.reshape(-1, 1)).toarray().astype(int)

#for i in xrange(len(state_holiday[0])):
#    df_test['state_holiday_type_{}'.format(i)] = state_holiday[:,i]
    
#df_test.drop(df_test[['StateHoliday']], axis=1, inplace=True)

В тестовых данных есть 11 объектов, у которых в столбце Open стоит nan. Заменим их на 1, и приведем весь столбец к целочисленному формату.

In [301]:
df_test.isnull().loc[:,'Open'].value_counts()

False    41077
True        11
Name: Open, dtype: int64

Присоединяем дополнительную таблицу

In [261]:
df_test_full = df_test.merge(df_store, on='Store', how='left')
df_test_full.head()

Store  DayOfWeek        Date  Open  Promo  StateHoliday  SchoolHoliday  \
0      1          4  2015-09-17   1.0      1             0              0   
1      3          4  2015-09-17   1.0      1             0              0   
2      7          4  2015-09-17   1.0      1             0              0   
3      8          4  2015-09-17   1.0      1             0              0   
4      9          4  2015-09-17   1.0      1             0              0   

   StoreType  Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0          2           0               1270.0                        9.0   
1          0           0              14130.0                       12.0   
2          0           2              24000.0                        4.0   
3          0           0               7520.0                       10.0   
4          0           2               2030.0                        8.0   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                    2008.0       0              NaN              NaN   
1                    2006.0       1             14.0           2011.0   
2                    2013.0       0              NaN              NaN   
3                    2014.0       0              NaN              NaN   
4                    2000.0       0              NaN              NaN   

     PromoInterval  
0              NaN  
1  Jan,Apr,Jul,Oct  
2              NaN  
3              NaN  
4              NaN

In [342]:
df_test_full['Open'].unique()

array([ 1.,  0.])

Заполняем пропуски в Open единицами (пропусков всего 11, так что это незначительно)

In [266]:
df_test_full.loc[df_test_full['Open'].isnull(), 'Open'] = 1

In [343]:
columns = ['Store', 'DayOfWeek', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance']
X_test_full = np.array(df_test_full.loc[:,columns]).astype(int)

In [347]:
np.unique(X_test_full[:, 2])

array([0, 1])

In [348]:
X_test_full.shape

(41088, 9)

In [337]:
np.unique(X_test_full[:,4])

array([0, 1])

In [284]:
X_test_full[:,0]

array([   1,    3,    7, ..., 1113, 1114, 1115])

<h2>Формат выходных данных</h2>

In [155]:
filepath = '/media/ivan/Acer/Ivan/sphere/Rossman/sample_submission.csv'
df_out = pd.read_csv(filepath, sep=',')
print len(df_out)
df_out.head()

41088


Id  Sales
0   1      0
1   2      0
2   3      0
3   4      0
4   5      0

<h2>Random Forest</h2>

In [86]:
from sklearn.ensemble import RandomForestRegressor

In [318]:
cls = RandomForestRegressor(n_estimators=30).fit(X_full, y_full)

In [319]:
cls.max_depth

In [349]:
score = cls.predict(X_test_full)

Получается, лес сам научился ставить 0, если магазин закрыт:

In [355]:
np.array_equal(score == 0, X_test_full[:,2] == 0)

True

Лучшая точность:<br>
<br>
0.16381<br>
0.14948<br>

In [302]:
from sklearn.model_selection import GridSearchCV

In [306]:
param_grid = {'max_depth': xrange(1, 21, 2), 'n_estimators': xrange(5, 101, 5)}
cls = RandomForestRegressor()
grid_search = GridSearchCV(cls, param_grid).fit(X_full[:10000], y_full[:10000])

In [307]:
grid_search.best_estimator_

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=19,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_split=1e-07, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [308]:
grid_search.best_score_

0.013052556414696301

<h2>Линейная регрессия</h2>

Векторизуем остальные категориальные признаки: DayOfWeek, StoreType, Assortment, и нормализуем вещественный CompetitionDistance

In [ ]:
df_full_linear = df_full
day_of_week = OneHotEncoder().fit_transform(df_full['DayOfWeek'].values.reshape(-1, 1)).toarray().astype(int)
store_type = OneHotEncoder().fit_transform(df_full['StoreType'].values.reshape(-1, 1)).toarray().astype(int)

for i in xrange(len(day_of_week[0])):
    df_full_linear['day_of_week_{}'.format(i)] = day_of_week[:,i]
    
for i in xrange(len(store_type[0])):
    df_full_linear['store_type_{}'.format(i)] = store_type[:,i]
    
df_test.drop(df_test[['DayOfWeek']], axis=1, inplace=True)

<h2>Запись в файл</h2>

In [326]:
df_out = pd.DataFrame(score, columns=['Sales'])

In [327]:
df_out = pd.DataFrame(score, columns=['Sales'])
df_out = df_out.reset_index().rename(index=str, columns={'index': 'Id'})
df_out.loc[:,'Id'] += 1
df_out.head()

Id        Sales
0   1  4996.272358
1   2  7910.144689
2   3  9023.591045
3   4  7105.741011
4   5  6599.713921

In [332]:
df_out['Sales'].isnull().unique()

array([False], dtype=object)

In [328]:
filepath = '/media/ivan/Acer/Ivan/sphere/Rossman/rossman.csv'
df_out.to_csv(filepath, index=False)

Проверка, что формат правильный:

In [329]:
filepath = '/media/ivan/Acer/Ivan/sphere/Rossman/rossman.csv'
df_out = pd.read_csv(filepath)
df_out.head()

Id        Sales
0   1  4996.272358
1   2  7910.144689
2   3  9023.591045
3   4  7105.741011
4   5  6599.713921

In [330]:
len(df_out)

41088